services:
  # Core services
  ultron-observer:
    image: ultron-observer
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ULTRON_SERVER_ADDRESS: ultron:8443
      ULTRON_REDIS_SERVER_ADDRESS: redis:6379
      ULTRON_REDIS_SERVER_PASSWORD: ${{ secrets.ULTRON_REDIS_SERVER_PASSWORD }}
      EMMA_CLIENT_ID: ${{ secrets.EMMA_CLIENT_ID }}
      EMMA_CLIENT_SECRET: ${{ secrets.EMMA_CLIENT_SECRET }}
    networks:
      - ultron
      
networks:
  ultron:
    external:
      name: ultron